### ISSUE TITLE
Do you mind 'tagging' or in github's terms adding 'topics' to this repo

### ISSUE THREAD

**Issue by luzpaz** [kogolbok/MyFreeCAD_Postprocessors#1]
like `freecad` 
You can also experiment with adding something like:`path` `postprocessor` `cnc` etc...
Thanks!

**Comment by kogolbok** [comment]
@luzpaz, Sorry?

**Comment by luzpaz** [comment]
@kogolbok https://help.github.com/articles/classifying-your-repository-with-topics/

**Comment by kogolbok** [comment]
Ah, didn't think of it. Thank you.

**Comment by luzpaz** [comment]
Cool! Cheers!
